com:
  xantech:
    mtgcardcollection:
        schedules:
          updateCardValueInterval: 3600000
          getInitialDelay: 1000
          dataValidInterval: 18000000
        mtggoldfish:
          throttelingPause: 1500